const fr = {
  origins: {
    acolyte: 'Acolyte',
    artisan: 'Artisan',
    charlatan: 'Charlatan',
    criminal: 'Criminel',
    entertainer: 'Artiste',
    farmer: 'Fermier',
    guard: 'Garde',
    guide: 'Guide',
    hermit: 'Ermite',
    merchant: 'Marchand',
    noble: 'Noble',
    sage: 'Sage',
    sailor: 'Marin',
    scribe: 'Scribe',
    soldier: 'Soldat',
    wayfarer: 'Voyageur',
  },
  skills: {
    'acrobatics': 'Acrobaties',
    'animalHandling': 'Dressage',
    'arcana': 'Arcanes',
    'athletics': 'Athlétisme',
    'deception': 'Tromperie',
    'history': 'Histoire',
    'insight': 'Perspicacité',
    'intimidation': 'Intimidation',
    'investigation': 'Investigation',
    'medicine': 'Médecine',
    'nature': 'Nature',
    'perception': 'Perception',
    'performance': 'Représentation',
    'persuasion': 'Persuasion',
    'religion': 'Religion',
    'sleightOfHand': 'Escamotage',
    'stealth': 'Discrétion',
    'survival': 'Survie',
  },
  classes: {
    barbarian: 'Barbare',
    bard: 'Barde',
    cleric: 'Clerc',
    druid: 'Druide',
    fighter: 'Guerrier',
    monk: 'Moine',
    paladin: 'Paladin',
    ranger: 'Rôdeur',
    rogue: 'Roublard',
    sorcerer: 'Ensorceleur',
    warlock: 'Occultiste',
    wizard: 'Magicien',
  }
}