const fr = {
  charName: {
    _label: 'Nom du personnage',
  },
  stats: {
    proficiencyBonus: 'Bonus de maîtrise',
    ability: {
      strength: 'Force',
      dexterity: 'Dextérité',
      constitution: 'Constitution',
      intelligence: 'Intelligence',
      wisdom: 'Sagesse',
      charisma: 'Charisme',
    },
    skills: {
      'acrobatics': 'Acrobaties',
      'animalHandling': 'Dressage',
      'arcana': 'Arcanes',
      'athletics': 'Athlétisme',
      'deception': 'Tromperie',
      'history': 'Histoire',
      'insight': 'Perspicacité',
      'intimidation': 'Intimidation',
      'investigation': 'Investigation',
      'medicine': 'Médecine',
      'nature': 'Nature',
      'perception': 'Perception',
      'performance': 'Représentation',
      'persuasion': 'Persuasion',
      'religion': 'Religion',
      'sleightOfHand': 'Escamotage',
      'stealth': 'Discrétion',
      'survival': 'Survie',
    },
    trainings: {
      title: 'Entraînements & Maîtrises',
      armor: {
        title: 'Armures',
        light: 'Légères',
        medium: 'Intermed.',
        heavy: 'Lourdes',
        shields: 'Boucliers',
      },
      weapon: {
        title: 'Armes',
      },
      tool: {
        title: 'Outils',
      }
    },
  },
  specs: {
    initiative: 'Initiative',
    speed: 'Vitesse',
    size: 'Taille',
    passivePerception: 'Perception Passive',
  },
  origins: {
    _label: 'Origine',
    acolyte: 'Acolyte',
    artisan: 'Artisan',
    charlatan: 'Charlatan',
    criminal: 'Criminel',
    entertainer: 'Artiste',
    farmer: 'Fermier',
    guard: 'Garde',
    guide: 'Guide',
    hermit: 'Ermite',
    merchant: 'Marchand',
    noble: 'Noble',
    sage: 'Sage',
    sailor: 'Marin',
    scribe: 'Scribe',
    soldier: 'Soldat',
    wayfarer: 'Voyageur',
  },
  classes: {
    _label: 'Classe',
    barbarian: 'Barbare',
    bard: 'Barde',
    cleric: 'Clerc',
    druid: 'Druide',
    fighter: 'Guerrier',
    monk: 'Moine',
    paladin: 'Paladin',
    ranger: 'Rôdeur',
    rogue: 'Roublard',
    sorcerer: 'Ensorceleur',
    warlock: 'Occultiste',
    wizard: 'Magicien',
  },
  races: {
    _label: 'Race',
    aasimar: 'Aasimar',
    dragonborn: 'Drakéide',
    dwarf: 'Nain',
    elf: 'Elfe',
    gnome: 'Gnome',
    goliath: 'Goliath',
    halfling: 'Halfelin',
    human: 'Humain',
    orc: 'Orc',
    tiefling: 'Tieffelin',
  },
  subClasses: {
    _label: 'Sous-classe',
    _select: 'Choisir une sous-classe',
    _unavailable: 'Dispo au niveau 3',
    barbarian: {
      berserker: 'Voie du Berserker',
      wildHeart: 'Voie du Coeur sauvage',
      worldTree: 'Voie de l\'Arbre-Monde',
      zealot: 'Voie du Zélateur',
    },
    bard: {
      dance: 'Collège de la Danse',
      glamour: 'Collège de la Séduction',
      lore: 'Collège du Savoir',
      valor: 'Collège de la Vaillance',
    },
    cleric: {
      life: 'Domaine de la Vie',
      light: 'Domaine de la Lumière',
      trickery: 'Domaine de la Ruse',
      war: 'Domaine de la Guerre',
    },
    druid: {
      land: 'Cercle de la Terre',
      moon: 'Cercle de la Lune',
      sea: 'Cercle des Mers',
      stars: 'Cercle des Astres',
    },
    fighter: {
      battleMaster: 'Maître de Guerre',
      champion: 'Champion',
      eldritchKnight: 'Chevalier Occulte',
      psiWarrior: 'Soldat Psi',
    },
    monk: {
      mercy: 'Credo de la Miséricorde',
      shadow: 'Credo de l\'Ombre',
      elements: 'Credo des éléments',
      openHand: 'Credo de la Paume',
    },
    paladin: {
      devotion: 'Serment de Dévotion',
      glory: 'Serment de la Gloire',
      ancients: 'Serment des Anciens',
      vengeance: 'Serment de Vengeance',
    },
    ranger: {
      beast: 'Belluaire',
      fey: 'Vagabond Féérique',
      stalker: 'Traqueur des Ténèbres',
      hunter: 'Chasseur',
    },
    rogue: {
      arcana: 'Arnaqueur Arcanique',
      assassin: 'Assassin',
      soulknife: 'Âme acérée',
      thief: 'Voleur',
    },
    sorcerer: {
      aberrant: 'Sorcellerie Aberrante',
      clockwork: 'Sorcellerie Mécanique',
      draconic: 'Sorcellerie Draconique',
      wild: 'Sorcellerie Sauvage',
    },
    warlock: {
      archfey: 'Protecteur Archifée',
      celestial: 'Protecteur Céleste',
      fiend: 'Protecteur Fiélon',
      old: 'Protecteur Grand Ancien',
    },
    wizard: {
      abjureur: 'Abjurateur',
      diviner: 'Devin',
      evoker: 'Evocateur',
      illusionist: 'Illusioniste',
    },
  },
  weaponClasses: {
    simpleMelee: 'Armes courantes de corps à corps',
    simpleRanged: 'Armes courantes à distance',
    martialMelee: 'Armes de guerre de corps à corps',
    martialRanged: 'Armes de guerre à distance',
  },
  weapons: {
    _select: 'Ajouter une arme',
    quarterstaff: 'Bâton de combat',
    dagger: 'Dague',
    club: 'Gourdin',
    handaxe: 'Hachette',
    javelin: 'Javeline',
    spear: 'Lance',
    lightHammer: 'Marteau léger',
    mace: 'Masse d’armes',
    greatclub: 'Massue',
    sickle: 'Serpe',
    lightCrossbow: 'Arbalète légère',
    shortbow: 'Arc court',
    dart: 'Fléchette',
    sling: 'Fronde',
    scimitar: 'Cimeterre',
    glaive: 'Coutille',
    greatSword: 'Épée à deux mains',
    shortSword: 'Épée courte',
    longSword: 'Épée longue',
    flail: 'Fléau d’armes',
    whip: 'Fouet',
    gretAxe: 'Hache à deux mains',
    battleAxe: `Hache d'armes`,
    halberd: 'Hallebarde',
    lance: 'Lance d’arçon',
    maul: 'Maillet d’armes',
    warhammer: 'Marteau de guerre',
    morningstar: 'Morgenstern',
    warPick: 'Pic de guerre',
    pike: 'Pique',
    rapier: 'Rapière',
    trident: 'Trident',
    handCrossbow: 'Arbalète de poing',
    heavyCrossbow: 'Arbalète lourde',
    longbow: 'Arc long',
    musket: 'Mousquet',
    pistol: 'Pistolet',
    blowgun: 'Sarbacane',
  }
}