export default {
  enlargeReduce: `Agrandissement/rapetissement`,
  aid: `Aide`,
  alarm: `Alarme`,
  befuddlement: `Aliénation`,
  planarAlly: `Allié planaire`,
  enhanceAbility: `Amélioration de caractéristique`,
  friends: `Amis|Faux amis`,
  animalFriendship: `Amitié avec les animaux`,
  animateDead: `Animation des morts`,
  animateObjects: `Animation des objets`,
  nondetection: `Antidétection`,
  calmEmotions: `Apaisement des émotions`,
  seeming: `Apparence trompeuse`,
  findSteed: `Appel de destrier`,
  findFamiliar: `Appel de familier`,
  callLightning: `Appel de la foudre`,
  elementalWeapon: `Arme élémentaire`,
  magicWeapon: `Arme magique`,
  spiritualWeapon: `Arme spirituelle`,
  armorOfAgathys: `Armure d'Agathys`,
  mageArmor: `Armure de mage`,
  timeStop: `Arrêt du temps`,
  acidSplash: `Aspersion d'acide`,
  phantasmalKiller: `Assassin imaginaire`,
  guidance: `Assistance`,
  augury: `Augure`,
  auraOfPurity: `Aura de pureté`,
  auraOfLife: `Aura de vie`,
  auraOfVitality: `Aura de vitalité`,
  crusadersMantle: `Aura du croisé`,
  nystulsMagicAura: `Aura magique de Nystul`,
  holyAura: `Aura sacrée`,
  antipathySympathy: `Aversion/attirance`,
  glibness: `Bagou`,
  goodberry: `Baies nourricières`,
  banishment: `Bannissement`,
  bladeBarrier: `Barrière de lames`,
  bless: `Bénédiction`,
  inflictWounds: `Blessure`,
  magicMouth: `Bouche magique`,
  shield: `Bouclier`,
  fireShield: `Bouclier de feu`,
  shieldOfFaith: `Bouclier de la foi`,
  poisonSpray: `Bouffée de poison`,
  fireball: `Boule de feu`,
  delayedBlastFireball: `Boule de feu à retardement`,
  gustOfWind: `Bourrasque`,
  cloudkill: `Brume mortelle`,
  forcecage: `Cage de force`,
  vampiricTouch: `Caresse du vampire`,
  blindnessDeafness: `Cécité/surdité`,
  circleOfDeath: `Cercle de mort`,
  circleOfPower: `Cercle de pouvoir`,
  teleportationCircle: `Cercle de téléportation`,
  magicCircle: `Cercle magique`,
  chainLightning: `Chaîne d'éclairs`,
  antimagicField: `Champ antimagie`,
  shapechange: `Changement de forme`,
  planeShift: `Changement de plan`,
  charmMonster: `Charme-monstre`,
  charmPerson: `Charme-personne`,
  blindingSmite: `Châtiment de cécité`,
  wrathfulSmite: `Châtiment de courroux`,
  searingSmite: `Châtiment de fournaise`,
  shiningSmite: `Châtiment de révélation`,
  staggeringSmite: `Châtiment de stupeur`,
  thunderousSmite: `Châtiment de tonnerre`,
  divineSmite: `Châtiment divin`,
  banishingSmite: `Châtiment du ban`,
  tashasBubblingCauldron: `Chaudron bouillonnant de Tasha`,
  mordenkainensFaithfulHound: `Chien de garde de Mordenkainen`,
  clairvoyance: `Clairvoyance`,
  blink: `Clignotement`,
  clone: `Clone`,
  leomundsSecretChest: `Coffre secret de Léomund`,
  flameStrike: `Colonne de flamme`,
  sending: `Communication à distance`,
  speakWithAnimals: `Communication avec les animaux`,
  speakWithDead: `Communication avec les morts`,
  speakWithPlants: `Communication avec les plantes`,
  commune: `Communion`,
  communeWithNature: `Communion avec la nature`,
  comprehendLanguages: `Compréhension des langues`,
  compulsion: `Compulsion`,
  coneOfCold: `Cône de froid`,
  confusion: `Confusion`,
  contactOtherPlane: `Contact avec les plans`,
  chillTouch: `Contact glacial`,
  contagion: `Contagion`,
  harm: `Contamination`,
  counterspell: `Contresort`,
  controlWater: `Contrôle de l'eau`,
  controlWeather: `Contrôle du climat`,
  summonAberration: `Convocation d'aberration`,
  summonConstruct: `Convocation d'artificiel`,
  summonElemental: `Convocation d'élémentaire`,
  summonBeast: `Convocation de bête`,
  summonCelestial: `Convocation de céleste`,
  summonDragon: `Convocation de dragon`,
  summonFey: `Convocation de fée`,
  summonFiend: `Convocation de fiélon`,
  summonUndead: `Convocation de mort-vivant`,
  drawmijsInstantSummons: `Convocations instantanées de Drawmij`,
  antilifeShell: `Coquille antivie`,
  ropeTrick: `Corde enchantée`,
  cordonOfArrows: `Cordon de flèches`,
  colorSpray: `Couleurs dansantes`,
  trueStrike: `Coup au but`,
  thunderclap: `Coup de tonnerre`,
  crownOfMadness: `Couronne du dément`,
  iceKnife: `Couteau de glace`,
  creation: `Création`,
  createUndead: `Création de mort-vivant`,
  createFoodAndWater: `Création de nourriture et d'eau`,
  createOrDestroyWater: `Création ou destruction d'eau`,
  spikeGrowth: `Croissance d'épines`,
  plantGrowth: `Croissance végétale`,
  shillelagh: `Crosse des druides`,
  ottosIrresistibleDance: `Danse irrésistible d'Otto`,
  knock: `Déblocage`,
  eldritchBlast: `Décharge occulte`,
  maze: `Dédale`,
  disguiseSelf: `Déguisement`,
  removeCurse: `Délivrance des malédictions`,
  demiplane: `Demi-plan`,
  disintegrate: `Désintégration`,
  seeInvisibility: `Détection de l'invisibilité`,
  detectMagic: `Détection de la magie`,
  detectThoughts: `Détection des pensées`,
  findTraps: `Détection des pièges`,
  detectEvilAndGood: `Détection du mal et du bien`,
  detectPoisonAndDisease: `Détection du poison et des maladies`,
  enthrall: `Discours captivant`,
  tensersFloatingDisk: `Disque flottant de Tenser`,
  sequester: `Dissimulation suprême`,
  dispelMagic: `Dissipation de la magie`,
  dispelEvilAndGood: `Dissipation du mal et du bien`,
  divination: `Divination`,
  fingerOfDeath: `Doigt de mort`,
  dominateBeast: `Domination de bête`,
  dominateMonster: `Domination de monstre`,
  dominatePerson: `Domination de personne`,
  tongues: `Don des langues`,
  mislead: `Double illusoire`,
  gentleRepose: `Doux repos`,
  druidcraft: `Druidisme`,
  compelledDuel: `Duel forcé`,
  lightningBolt: `Éclair`,
  sunburst: `Éclat du soleil`,
  elementalism: `Élémentalisme`,
  prismaticSpray: `Embruns prismatiques`,
  imprisonment: `Emprisonnement`,
  entangle: `Enchevêtrement`,
  weird: `Ennemi subconscient`,
  planarBinding: `Entrave planaire`,
  mordenkainensSword: `Épée de Mordenkainen`,
  mindSpike: `Épine mentale`,
  sorcerousBurst: `Éruption ensorcelée`,
  mindBlank: `Esprit impénétrable`,
  spiritGuardians: `Esprits gardiens`,
  feignDeath: `État cadavérique`,
  awaken: `Éveil`,
  fabricate: `Fabrication`,
  stoneShape: `Façonnage de la pierre`,
  divineFavor: `Faveur divine`,
  heroesFeast: `Festin des héros`,
  featherFall: `Feuille morte`,
  continualFlame: `Flamme éternelle`,
  sacredFlame: `Flamme sacrée`,
  produceFlame: `Flammes`,
  insectPlague: `Fléau d'insectes`,
  melfsAcidArrow: `Flèche acide de Melf`,
  lightningArrow: `Flèche de foudre`,
  blight: `Flétrissement`,
  blur: `Flou`,
  fountOfMoonlight: `Fontaine de lune`,
  phantasmalForce: `Force fantasmagorique`,
  etherealness: `Forme éthérée`,
  gaseousForm: `Forme gazeuse`,
  tashasHideousLaughter: `Fou rire de Tasha`,
  thornWhip: `Fouet épineux`,
  mistyStep: `Foulée brumeuse`,
  shatter: `Fracassement`,
  steelWindStrike: `Frappe du vent d'acier`,
  ensnaringStrike: `Frappe piégeuse`,
  meldIntoStone: `Fusion dans la pierre`,
  guardianOfFaith: `Gardien de la foi`,
  tollTheDead: `Glas`,
  moveEarth: `Glissement de terrain`,
  globeOfInvulnerability: `Globe d'invulnérabilité`,
  glyphOfWarding: `Glyphe de garde`,
  grease: `Graisse`,
  longstrider: `Grande foulée`,
  hailOfThorns: `Grêle d'épines`,
  heal: `Guérison`,
  massHeal: `Guérison de groupe`,
  haste: `Hâte`,
  heroism: `Héroïsme`,
  identify: `Identification`,
  minorIllusion: `Illusion mineure`,
  programmedIllusion: `Illusion programmée`,
  majorImage: `Image majeure`,
  mirrorImage: `Image miroir`,
  projectImage: `Image projetée`,
  silentImage: `Image silencieuse`,
  holdMonster: `Immobilisation de monstre`,
  holdPerson: `Immobilisation de personne`,
  bane: `Imprécation`,
  command: `Injonction`,
  giantInsect: `Insecte géant`,
  forbiddance: `Interdiction`,
  reverseGravity: `Inversion de la gravité`,
  invisibility: `Invisibilité`,
  greaterInvisibility: `Invisibilité suprême`,
  conjureAnimals: `Invocation d'animaux`,
  conjureElemental: `Invocation d'élémentaire`,
  conjureMinorElementals: `Invocation d'élémentaires mineurs`,
  conjureWoodlandBeings: `Invocation d'êtres sylvestres`,
  conjureCelestial: `Invocation de céleste`,
  conjureFey: `Invocation de fée`,
  conjureBarrage: `Invocation de projectiles|Hérissement`,
  conjureVolley: `Invocation de volée`,
  flameBlade: `Lame de feu`,
  slow: `Lenteur`,
  levitate: `Lévitation`,
  graspingVine: `Liane avide`,
  freedomOfMovement: `Liberté de mouvement`,
  wardingBond: `Lien de protection`,
  rarysTelepathicBond: `Lien télépathique de Rary`,
  locateAnimalsOrPlants: `Localisation d'animaux ou de plantes`,
  locateObject: `Localisation d'objet`,
  locateCreature: `Localisation de créature`,
  beaconOfHope: `Lueur d'espoir`,
  faerieFire: `Lueurs féeriques`,
  light: `Lumière`,
  daylight: `Lumière du jour`,
  dancingLights: `Lumières dansantes`,
  bigbysHand: `Main de Bigby`,
  mageHand: `Main de mage`,
  burningHands: `Mains brûlantes`,
  bestowCurse: `Malédiction`,
  hex: `Maléfice`,
  mordenkainensMagnificentMansion: `Manoir somptueux de Mordenkainen`,
  waterWalk: `Marche sur l'eau|Marche sur l'onde`,
  huntersMark: `Marque du chasseur`,
  eyebite: `Mauvais oeil`,
  message: `Message`,
  animalMessenger: `Messager animal`,
  heatMetal: `Métal brûlant`,
  polymorph: `Métamorphose`,
  animalShapes: `Métamorphose animale`,
  truePolymorph: `Métamorphose suprême`,
  mirageArcane: `Mirage`,
  alterSelf: `Modification d'apparence`,
  modifyMemory: `Modification de mémoire`,
  phantomSteed: `Monture fantôme`,
  viciousMockery: `Moquerie cruelle`,
  healingWord: `Mot de guérison`,
  massHealingWord: `Mot de guérison de groupe`,
  powerWordStun: `Mot de pouvoir étourdissant`,
  powerWordFortify: `Mot de pouvoir fortifiant`,
  powerWordHeal: `Mot de pouvoir guérisseur`,
  powerWordKill: `Mot de pouvoir mortel`,
  wordOfRadiance: `Mot de radiance`,
  wordOfRecall: `Mot de retour`,
  hypnoticPattern: `Motif hypnotique`,
  wallOfThorns: `Mur d'épines`,
  wallOfFire: `Mur de feu`,
  wallOfForce: `Mur de force`,
  wallOfIce: `Mur de glace`,
  wallOfStone: `Mur de pierre`,
  windWall: `Mur de vent`,
  prismaticWall: `Mur prismatique`,
  dissonantWhispers: `Murmures dissonants`,
  legendLore: `Mythes et légendes`,
  fogCloud: `Nappe de brouillard`,
  incendiaryCloud: `Nuage incendiaire`,
  stinkingCloud: `Nuage nauséabond`,
  cloudOfDaggers: `Nuée de dagues`,
  meteorSwarm: `Nuée de météores`,
  arcaneEye: `Oeil du mage`,
  chromaticOrb: `Orbe chromatique`,
  findThePath: `Orientation`,
  divineWord: `Parole divine`,
  treeStride: `Passage par les arbres`,
  passWithoutTrace: `Passage sans trace`,
  passwall: `Passe-muraille`,
  spiderClimb: `Pattes d'araignée`,
  barkskin: `Peau d'écorce`,
  stoneskin: `Peau de pierre`,
  beastSense: `Perception bestiale`,
  synapticStatic: `Perturbations synaptiques`,
  leomundsTinyHut: `Petite hutte de Léomund`,
  fleshToStone: `Pétrification`,
  fear: `Peur|Terreur`,
  mindSliver: `Piqûre mentale`,
  shockingGrasp: `Poigne électrique`,
  gate: `Portail`,
  arcaneGate: `Portail arcanique`,
  dimensionDoor: `Porte dimensionnelle`,
  starryWisp: `Poussière d'étoile`,
  contingency: `Préméditation`,
  foresight: `Prémonition`,
  yolandesRegalPresence: `Présence royale de Yolane`,
  prestidigitation: `Prestidigitation`,
  prayerOfHealing: `Prière de guérison`,
  magicMissile: `Projectile magique`,
  astralProjection: `Projection astrale`,
  protectionFromEnergy: `Protection contre l'énergie`,
  deathWard: `Protection contre la mort`,
  protectionFromEvilAndGood: `Protection contre le mal et le bien`,
  protectionFromPoison: `Protection contre le poison`,
  guardsAndWards: `Protections et sceaux`,
  purifyFoodAndDrink: `Purification de la nourriture et de l'eau`,
  geas: `Quête`,
  raiseDead: `Rappel à la vie`,
  rayOfEnfeeblement: `Rayon affaiblissant`,
  scorchingRay: `Rayon ardent`,
  rayOfFrost: `Rayon de givre`,
  moonbeam: `Rayon de lune`,
  sunbeam: `Rayon de soleil`,
  rayOfSickness: `Rayon empoisonné`,
  guidingBolt: `Rayon traçant`,
  regenerate: `Régénération`,
  reincarnate: `Réincarnation`,
  mending: `Réparation`,
  expeditiousRetreat: `Repli expéditif`,
  hellishRebuke: `Représailles infernales`,
  resistance: `Résistance`,
  waterBreathing: `Respiration aquatique`,
  lesserRestoration: `Restauration partielle`,
  greaterRestoration: `Restauration suprême`,
  resurrection: `Résurrection`,
  trueResurrection: `Résurrection suprême`,
  revivify: `Retour à la vie`,
  hallow: `Sanctification`,
  sanctuary: `Sanctuaire`,
  mordenkainensPrivateSanctum: `Sanctuaire privé de Mordenkainen`,
  jump: `Saut`,
  scrying: `Scrutation`,
  unseenServant: `Serviteur invisible`,
  silence: `Silence`,
  simulacrum: `Simulacre`,
  falseLife: `Simulacre de vie`,
  cureWounds: `Soins`,
  massCureWounds: `Soins de groupe`,
  sleep: `Sommeil`,
  dream: `Songe`,
  dragonsBreath: `Souffle du dragon`,
  wish: `Souhait`,
  flamingSphere: `Sphère de feu`,
  vitriolicSphere: `Sphère de vitriol`,
  otilukesFreezingSphere: `Sphère glacée d'Otiluke`,
  otilukesResilientSphere: `Sphère résiliente d'Otiluke`,
  spareTheDying: `Stabilisation`,
  suggestion: `Suggestion`,
  massSuggestion: `Suggestion de groupe`,
  symbol: `Symbole`,
  telekinesis: `Télékinésie`,
  telepathy: `Télépathie`,
  teleport: `Téléportation`,
  fireStorm: `Tempête de feu`,
  iceStorm: `Tempête de grêle`,
  sleetStorm: `Tempête de neige`,
  jallarzisStormOfRadiance: `Tempête radieuse de Jallarzi`,
  stormOfVengeance: `Tempête vengeresse`,
  darkness: `Ténèbres`,
  armsOfHadar: `Tentacules de Hadar`,
  evardsBlackTentacles: `Tentacules noirs d'Evard`,
  hallucinatoryTerrain: `Terrain hallucinatoire`,
  illusoryScript: `Texte illusoire`,
  thaumaturgy: `Thaumaturgie`,
  web: `Toile d'araignée`,
  fireBolt: `Trait de feu`,
  witchBolt: `Trait ensorcelé`,
  earthquake: `Tremblement de terre`,
  tsunami: `Tsunami`,
  magicJar: `Urne magique|Possession`,
  destructiveWave: `Vague destructrice`,
  thunderwave: `Vague tonnante`,
  windWalk: `Vent divin`,
  arcaneLock: `Verrou arcanique|Verrou magique`,
  swiftQuiver: `Vif carquois`,
  arcaneVigor: `Vigueur arcanique`,
  darkvision: `Vision dans le noir`,
  trueSeeing: `Vision suprême`,
  transportViaPlants: `Voie végétale`,
  bladeWard: `Voile défensif`,
  fly: `Vol`,
  hungerOfHadar: `Voracité de Hadar`,
  zoneOfTruth: `Zone de vérité`,
}